version: '3.8'
services:
  node-server:
    build: .
    image: node-server
    container_name: node-server
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules/
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: shared_network
